version: '3'
services:
  engine:
    build: .
    volumes:
      - "./:/usr/data/graph-engine/"
    ports:
      - "3000:3000"
      - "9229:9229" #for debug
    environment:
      - PORT=3000
    command: npm run start
  orientdb:
    image: orientdb:3.0.19
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: 'foo'
    volumes:
      - ./orientdb/config:/opt/orientdb/config
      - ./orientdb/databases:/opt/orientdb/databases
      - ./orientdb/backup:/opt/orientdb/backup
  nats:
    image: nats:1.4.1-linux
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"